name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.team_g0GNiZS0zgPgwxg6Yru2Dq77 }}
  VERCEL_PROJECT_ID: ${{ secrets.prj_jIL8AEeJNMF3SkTcBqGaAJOMGXKc }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.fTtReuZg13ldPFoL96YsODbo }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.fTtReuZg13ldPFoL96YsODbo }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.fTtReuZg13ldPFoL96YsODbo }}
